#!/bin/bash
# For non-OS X systems, a placeholder for the program from
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
if [[ `uname` = "Darwin" ]]; then
    if [[ `uname -m` = "arm64" ]]; then
    	exec /opt/homebrew/bin/reattach-to-user-namespace -l zsh
    else
    	exec /usr/local/bin/reattach-to-user-namespace -l zsh
    fi
else
    exec "$@"
fi
